#H2 connection config
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb

# OracleDB connection config
#spring:
  #datasource:
    #url: jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
    #username: rm93915
    #password: 060696
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update


server:
  error:
    include-stacktrace: never

#Folder images directory
image:
  upload:
    directory: ${user.dir}/images

#imageSize
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# Oauth2 Google Provider
security:
  oauth2:
    client:
      registration:
        google:
          clientId: 171995458014-i1g4bsllj4vkmb1j8jo3mnr7nn6cuf04.apps.googleusercontent.com
          clientSecret: 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

# JWT Secret
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 3600000
  # CorsConfig
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://192.168.0.26:8081/oauth2/redirect
      - myiosapp://oauth2/redirect


