#H2 connection config
spring:
  datasource:
    url: jdbc:h2:mem:testdb
server:
  error:
    include-stacktrace: never
  profile:
    active:${ACTIVE_PROFILE:local}
#Folder images directory
image:
  upload:
    directory: ${user.dir}/images

  #imageSize
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Oauth2 Google Provider
security:
  oauth2:
    client:
      registration:
        google:
          clientId: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_SECRET}

# JWT Secret
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 3600000
  # CorsConfig
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://192.168.0.26:8081/oauth2/redirect
      - myiosapp://oauth2/redirect
